## **2.Import required library**

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras_preprocessing import sequence
from keras.utils import to_categorical
from keras.models import load_model

## **3.Read Dataset and do preprocessing**

In [53]:
df = pd.read_csv('/content/spam.csv',delimiter=',',encoding='latin-1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [54]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [55]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True) #dropping unwanted columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [56]:
# Count of Spam and Ham values
df.groupby(['v1']).size()

v1
ham     4825
spam     747
dtype: int64

In [57]:
# Label Encoding target column
X = df.v2
Y = df.v1
le = LabelEncoder()
Y = le.fit_transform(Y)
Y = Y.reshape(-1,1)

In [58]:
# Test and train split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15)

In [59]:
cd ..

/


In [60]:
pwd

'/'

In [61]:
train_set = df.iloc[:,2:5572].values

In [62]:
train_set

array([], shape=(5572, 0), dtype=float64)

In [63]:
#Applying Scaling

In [64]:
X = df.v2
Y = df.v1
le = LabelEncoder()
Y = le.fit_transform(Y)
Y = Y.reshape(-1,1)

In [65]:
from keras.preprocessing import sequence

In [66]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15)

In [67]:
Y_train

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [68]:
len(X_train)

4736

In [69]:
len(Y_train)

4736

In [70]:
X_train, Y_train=np.array(X_train),np.array(Y_train)

In [71]:
X_train.shape

(4736,)

In [72]:
Y_train.shape

(4736, 1)

In [73]:
X_train.ndim

1

In [74]:
np.arange(0)

array([], dtype=int64)

In [75]:
p=np.arange(9).reshape(3,3,1)

In [76]:
p

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [77]:
X_train = np.reshape(X_train,(4736,1,1 ))

In [78]:
X_train.ndim

3

In [79]:
X_train.shape[1]

1

## **4.Create Model and 5. Add Layers (LSTM, Dense-(Hidden Layers), Output)**

In [81]:
# Creating LSTM model
inputs = Input(name='InputLayer',shape=[max_len])
layer = Embedding(max_words,50,input_length=max_len)(inputs)
layer = LSTM(64)(layer)
layer = Dense(256,name='FullyConnectedLayer1')(layer)
layer = Activation('relu')(layer)
layer = Dropout(0.5)(layer)
layer = Dense(1,name='OutputLayer')(layer)
layer = Activation('sigmoid')(layer)

## **6.Compile the model**

In [82]:
model = Model(inputs=inputs,outputs=layer)
model.summary()
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 InputLayer (InputLayer)     [(None, 150)]             0         
                                                                 
 embedding_1 (Embedding)     (None, 150, 50)           50000     
                                                                 
 lstm_1 (LSTM)               (None, 64)                29440     
                                                                 
 FullyConnectedLayer1 (Dense  (None, 256)              16640     
 )                                                               
                                                                 
 activation_2 (Activation)   (None, 256)               0         
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                           

## **7.Fit the Model**

In [83]:
model.fit(sequences_matrix,Y_train,batch_size=128,epochs=10,
          validation_split=0.2)

Epoch 1/10
30/30 [==============================] - 12s 272ms/step - loss: 0.4417 - accuracy: 0.8501 - val_loss: 0.3904 - val_accuracy: 0.8681
Epoch 2/10
30/30 [==============================] - 7s 241ms/step - loss: 0.3970 - accuracy: 0.8667 - val_loss: 0.3962 - val_accuracy: 0.8681
Epoch 3/10
30/30 [==============================] - 7s 244ms/step - loss: 0.3917 - accuracy: 0.8667 - val_loss: 0.3906 - val_accuracy: 0.8681
Epoch 4/10
30/30 [==============================] - 7s 244ms/step - loss: 0.3735 - accuracy: 0.8667 - val_loss: 0.4012 - val_accuracy: 0.8681
Epoch 5/10
30/30 [==============================] - 7s 241ms/step - loss: 0.3462 - accuracy: 0.8672 - val_loss: 0.4258 - val_accuracy: 0.8660
Epoch 6/10
30/30 [==============================] - 7s 247ms/step - loss: 0.3289 - accuracy: 0.8685 - val_loss: 0.4523 - val_accuracy: 0.8608
Epoch 7/10
30/30 [==============================] - 7s 239ms/step - loss: 0.3158 - accuracy: 0.8699 - val_loss: 0.5426 - val_accuracy: 0.8629
Epoch

# **8.Save the Model**

In [84]:
model.save("model_1")

# **9.Test the model**

In [87]:
accuracy = model.evaluate(test_sequences_matrix,Y_test)
print('Accuracy: {:0.3f}'.format(accuracy[1]))

27/27 [==============================] - 1s 21ms/step - loss: 0.5337 - accuracy: 0.8050
Accuracy: 0.805


In [88]:
y_pred = model.predict(test_sequences_matrix)
print(y_pred[25:40].round(3))

27/27 [==============================] - 1s 21ms/step
[[0.004]
 [0.013]
 [0.03 ]
 [0.052]
 [0.056]
 [0.013]
 [0.164]
 [0.137]
 [0.047]
 [0.055]
 [0.035]
 [0.22 ]
 [0.066]
 [0.151]
 [0.003]]


In [89]:
print(Y_test[25:40])

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]]


In [90]:
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accuracy[0],accuracy[1]))

Test set
  Loss: 0.534
  Accuracy: 0.805
